/**
 * Contract-adjacent sales screens.
 *
 * - salesContractUpload: TBIZ037 planning/view/performance upload rows.
 * - salesPlanViewPerformance: TBIZ050 plan/view/performance master rows.
 * - salesPlanViewPerformanceMonth: TBIZ051 monthly details.
 * - salesPlanAcl: Jarvis row ACL for plan/view/performance master rows.
 */

import {
  boolean,
  index,
  numeric,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";
import { user } from "./user.js";

export const salesContractUpload = pgTable(
  "sales_contract_upload",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id").notNull(),
    legacyEnterCd: varchar("legacy_enter_cd", { length: 10 }),
    ym: varchar("ym", { length: 6 }).notNull(),
    inOutType: varchar("in_out_type", { length: 10 }),
    costCd: varchar("cost_cd", { length: 20 }).notNull(),
    costGrpNm: varchar("cost_grp_nm", { length: 200 }),
    costNm: varchar("cost_nm", { length: 200 }),
    productType: varchar("product_type", { length: 20 }).notNull(),
    contType: varchar("cont_type", { length: 20 }).notNull(),
    companyCd: varchar("company_cd", { length: 50 }).notNull(),
    companyNm: varchar("company_nm", { length: 300 }),
    pjtCode: varchar("pjt_code", { length: 50 }).notNull(),
    pjtNm: varchar("pjt_nm", { length: 300 }),
    sucProb: varchar("suc_prob", { length: 10 }),
    planServSaleAmt: numeric("plan_serv_sale_amt"),
    planProdSaleAmt: numeric("plan_prod_sale_amt"),
    planInfSaleAmt: numeric("plan_inf_sale_amt"),
    planServOutCostAmt: numeric("plan_serv_out_cost_amt"),
    planProdCostAmt: numeric("plan_prod_cost_amt"),
    planRentAmt: numeric("plan_rent_amt"),
    planExpAmt: numeric("plan_exp_amt"),
    planSgaAmt: numeric("plan_sga_amt"),
    planInCostAmt: numeric("plan_in_cost_amt"),
    planOutCostAmt: numeric("plan_out_cost_amt"),
    planIndirectGrpAmt: numeric("plan_indirect_grp_amt"),
    planIndirectComAmt: numeric("plan_indirect_com_amt"),
    planInManMonth: numeric("plan_in_man_month", { precision: 15, scale: 10 }),
    planOutManMonth: numeric("plan_out_man_month", { precision: 15, scale: 10 }),
    viewServSaleAmt: numeric("view_serv_sale_amt"),
    viewProdSaleAmt: numeric("view_prod_sale_amt"),
    viewInfSaleAmt: numeric("view_inf_sale_amt"),
    viewServOutCostAmt: numeric("view_serv_out_cost_amt"),
    viewProdCostAmt: numeric("view_prod_cost_amt"),
    viewRentAmt: numeric("view_rent_amt"),
    viewExpAmt: numeric("view_exp_amt"),
    viewSgaAmt: numeric("view_sga_amt"),
    viewInCostAmt: numeric("view_in_cost_amt"),
    viewOutCostAmt: numeric("view_out_cost_amt"),
    viewIndirectGrpAmt: numeric("view_indirect_grp_amt"),
    viewIndirectComAmt: numeric("view_indirect_com_amt"),
    viewInManMonth: numeric("view_in_man_month", { precision: 15, scale: 10 }),
    viewOutManMonth: numeric("view_out_man_month", { precision: 15, scale: 10 }),
    perfServSaleAmt: numeric("perf_serv_sale_amt"),
    perfProdSaleAmt: numeric("perf_prod_sale_amt"),
    perfInfSaleAmt: numeric("perf_inf_sale_amt"),
    perfServOutCostAmt: numeric("perf_serv_out_cost_amt"),
    perfProdCostAmt: numeric("perf_prod_cost_amt"),
    perfRentAmt: numeric("perf_rent_amt"),
    perfExpAmt: numeric("perf_exp_amt"),
    perfSgaAmt: numeric("perf_sga_amt"),
    perfInCostAmt: numeric("perf_in_cost_amt"),
    perfOutCostAmt: numeric("perf_out_cost_amt"),
    perfIndirectGrpAmt: numeric("perf_indirect_grp_amt"),
    perfIndirectComAmt: numeric("perf_indirect_com_amt"),
    perfInManMonth: numeric("perf_in_man_month", { precision: 15, scale: 10 }),
    perfOutManMonth: numeric("perf_out_man_month", { precision: 15, scale: 10 }),
    note: text("note"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }),
    createdBy: uuid("created_by"),
    updatedBy: uuid("updated_by"),
  },
  (t) => ({
    wsYmIdx: index("sales_contract_upload_ws_ym_idx").on(t.workspaceId, t.ym),
    wsCompanyIdx: index("sales_contract_upload_ws_company_idx").on(t.workspaceId, t.companyCd),
    legacyUniq: uniqueIndex("sales_contract_upload_legacy_uniq").on(
      t.workspaceId,
      t.ym,
      t.costCd,
      t.companyCd,
      t.productType,
      t.contType,
      t.pjtCode,
    ),
  }),
);

export const salesPlanViewPerformance = pgTable(
  "sales_plan_view_performance",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id").notNull(),
    legacyEnterCd: varchar("legacy_enter_cd", { length: 10 }),
    dataType: varchar("data_type", { length: 20 }).notNull(),
    companyCd: varchar("company_cd", { length: 50 }).notNull(),
    costCd: varchar("cost_cd", { length: 20 }).notNull(),
    pjtCode: varchar("pjt_code", { length: 50 }).notNull(),
    contYear: varchar("cont_year", { length: 4 }).notNull(),
    pjtNm: varchar("pjt_nm", { length: 300 }),
    companyNo: varchar("company_no", { length: 40 }),
    companyNm: varchar("company_nm", { length: 300 }),
    companyType: varchar("company_type", { length: 20 }),
    inOutType: varchar("in_out_type", { length: 10 }),
    title: varchar("title", { length: 300 }),
    custNm: varchar("cust_nm", { length: 200 }),
    contGbCd: varchar("cont_gb_cd", { length: 20 }),
    contYmd: varchar("cont_ymd", { length: 8 }),
    contSymd: varchar("cont_symd", { length: 8 }),
    contEymd: varchar("cont_eymd", { length: 8 }),
    newYn: varchar("new_yn", { length: 1 }),
    contType: varchar("cont_type", { length: 20 }),
    productType: varchar("product_type", { length: 20 }),
    totOrderAmt: numeric("tot_order_amt"),
    serOrderAmt: numeric("ser_order_amt"),
    prdOrderAmt: numeric("prd_order_amt"),
    infOrderAmt: numeric("inf_order_amt"),
    servAmt: numeric("serv_amt"),
    prodAmt: numeric("prod_amt"),
    inManMonth: numeric("in_man_month", { precision: 15, scale: 10 }),
    outManMonth: numeric("out_man_month", { precision: 15, scale: 10 }),
    sgaAmt: numeric("sga_amt"),
    expAmt: numeric("exp_amt"),
    changeReason: text("change_reason"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }),
    createdBy: uuid("created_by"),
    updatedBy: uuid("updated_by"),
  },
  (t) => ({
    wsYearIdx: index("sales_plan_view_perf_ws_year_idx").on(t.workspaceId, t.contYear),
    wsCompanyIdx: index("sales_plan_view_perf_ws_company_idx").on(t.workspaceId, t.companyCd),
    legacyUniq: uniqueIndex("sales_plan_view_perf_legacy_uniq").on(
      t.workspaceId,
      t.dataType,
      t.companyCd,
      t.costCd,
      t.pjtCode,
      t.contYear,
    ),
  }),
);

export const salesPlanViewPerformanceMonth = pgTable(
  "sales_plan_view_performance_month",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id").notNull(),
    planId: uuid("plan_id")
      .notNull()
      .references(() => salesPlanViewPerformance.id, { onDelete: "cascade" }),
    ym: varchar("ym", { length: 6 }).notNull(),
    serOrderAmt: numeric("ser_order_amt"),
    prdOrderAmt: numeric("prd_order_amt"),
    infOrderAmt: numeric("inf_order_amt"),
    servAmt: numeric("serv_amt"),
    prodAmt: numeric("prod_amt"),
    inManMonth: numeric("in_man_month", { precision: 15, scale: 10 }),
    outManMonth: numeric("out_man_month", { precision: 15, scale: 10 }),
    dirInAmt: numeric("dir_in_amt"),
    dirOutAmt: numeric("dir_out_amt"),
    indirOrgAmt: numeric("indir_org_amt"),
    indirAllAmt: numeric("indir_all_amt"),
    sgaAmt: numeric("sga_amt"),
    expAmt: numeric("exp_amt"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }),
    createdBy: uuid("created_by"),
    updatedBy: uuid("updated_by"),
  },
  (t) => ({
    planYmUniq: uniqueIndex("sales_plan_view_perf_month_plan_ym_uniq").on(t.planId, t.ym),
    wsYmIdx: index("sales_plan_view_perf_month_ws_ym_idx").on(t.workspaceId, t.ym),
  }),
);

export const salesPlanAcl = pgTable(
  "sales_plan_acl",
  {
    planId: uuid("plan_id")
      .notNull()
      .references(() => salesPlanViewPerformance.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    canRead: boolean("can_read").default(true).notNull(),
    canWrite: boolean("can_write").default(false).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    pk: primaryKey({ columns: [t.planId, t.userId] }),
  }),
);
