export const PERMISSIONS = {
  KNOWLEDGE_READ: "knowledge:read",
  KNOWLEDGE_CREATE: "knowledge:create",
  KNOWLEDGE_UPDATE: "knowledge:update",
  KNOWLEDGE_DELETE: "knowledge:delete",
  KNOWLEDGE_REVIEW: "knowledge:review",
  KNOWLEDGE_ADMIN: "knowledge:admin",

  PROJECT_READ: "project:read",
  PROJECT_CREATE: "project:create",
  PROJECT_UPDATE: "project:update",
  PROJECT_DELETE: "project:delete",
  PROJECT_ADMIN: "project:admin",

  SYSTEM_READ: "system:read",
  SYSTEM_CREATE: "system:create",
  SYSTEM_UPDATE: "system:update",
  SYSTEM_DELETE: "system:delete",
  SYSTEM_ACCESS_SECRET: "system.access:secret",

  ATTENDANCE_READ: "attendance:read",
  ATTENDANCE_WRITE: "attendance:write",
  ATTENDANCE_ADMIN: "attendance:admin",

  USER_READ: "admin:users:read",
  USER_WRITE: "admin:users:write",
  AUDIT_READ: "admin:audit:read",
  ADMIN_ALL: "admin:all",
  FILES_WRITE: "files:write",

  GRAPH_READ: "graph:read",
  GRAPH_BUILD: "graph:build"
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  ADMIN: Object.values(PERMISSIONS) as Permission[],
  MANAGER: [
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.KNOWLEDGE_CREATE,
    PERMISSIONS.KNOWLEDGE_UPDATE,
    PERMISSIONS.KNOWLEDGE_REVIEW,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.SYSTEM_READ,
    PERMISSIONS.SYSTEM_CREATE,
    PERMISSIONS.SYSTEM_UPDATE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_ADMIN,
    PERMISSIONS.USER_READ,
    PERMISSIONS.FILES_WRITE,
    PERMISSIONS.GRAPH_READ,
    PERMISSIONS.GRAPH_BUILD
  ],
  DEVELOPER: [
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.KNOWLEDGE_CREATE,
    PERMISSIONS.KNOWLEDGE_UPDATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.SYSTEM_READ,
    PERMISSIONS.SYSTEM_ACCESS_SECRET,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.FILES_WRITE,
    PERMISSIONS.GRAPH_READ,
    PERMISSIONS.GRAPH_BUILD
  ],
  HR: [
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_ADMIN
  ],
  VIEWER: [
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.SYSTEM_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.GRAPH_READ
  ]
};
