export const PERMISSIONS = {
  KNOWLEDGE_READ: "knowledge:read",
  KNOWLEDGE_CREATE: "knowledge:create",
  KNOWLEDGE_UPDATE: "knowledge:update",
  KNOWLEDGE_DELETE: "knowledge:delete",
  KNOWLEDGE_REVIEW: "knowledge:review",
  KNOWLEDGE_ADMIN: "knowledge:admin",

  PROJECT_READ: "project:read",
  PROJECT_CREATE: "project:create",
  PROJECT_UPDATE: "project:update",
  PROJECT_DELETE: "project:delete",
  PROJECT_ACCESS_SECRET: "project.access:secret",

  ADDITIONAL_DEV_READ: "additional-dev:read",
  ADDITIONAL_DEV_CREATE: "additional-dev:create",
  ADDITIONAL_DEV_UPDATE: "additional-dev:update",
  ADDITIONAL_DEV_DELETE: "additional-dev:delete",

  USER_READ: "admin:users:read",
  USER_WRITE: "admin:users:write",
  AUDIT_READ: "admin:audit:read",
  ADMIN_ALL: "admin:all",
  FILES_WRITE: "files:write",

  GRAPH_READ: "graph:read",
  GRAPH_BUILD: "graph:build",

  NOTICE_READ: "notice:read",
  NOTICE_CREATE: "notice:create",
  NOTICE_UPDATE: "notice:update",
  NOTICE_DELETE: "notice:delete"
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  ADMIN: Object.values(PERMISSIONS) as Permission[],
  MANAGER: [
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.KNOWLEDGE_CREATE,
    PERMISSIONS.KNOWLEDGE_UPDATE,
    PERMISSIONS.KNOWLEDGE_REVIEW,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.ADDITIONAL_DEV_READ,
    PERMISSIONS.ADDITIONAL_DEV_CREATE,
    PERMISSIONS.ADDITIONAL_DEV_UPDATE,
    PERMISSIONS.ADDITIONAL_DEV_DELETE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.FILES_WRITE,
    PERMISSIONS.GRAPH_READ,
    PERMISSIONS.GRAPH_BUILD,
    PERMISSIONS.NOTICE_READ,
    PERMISSIONS.NOTICE_CREATE,
    PERMISSIONS.NOTICE_UPDATE
  ],
  // Phase-W3 RBAC 참고:
  // DEVELOPER는 KNOWLEDGE_REVIEW가 없으므로, wiki_page_index의 sensitivity='RESTRICTED'
  // 페이지가 검색·AI 결과에서 제외됩니다 (buildWikiSensitivitySqlFilter 엄격 규약).
  // RESTRICTED 위키 접근이 필요한 DEVELOPER는 MANAGER 권한을 추가로 부여받아야 합니다.
  DEVELOPER: [
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.KNOWLEDGE_CREATE,
    PERMISSIONS.KNOWLEDGE_UPDATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_ACCESS_SECRET,
    PERMISSIONS.ADDITIONAL_DEV_READ,
    PERMISSIONS.ADDITIONAL_DEV_UPDATE,
    PERMISSIONS.FILES_WRITE,
    PERMISSIONS.GRAPH_READ,
    PERMISSIONS.GRAPH_BUILD,
    PERMISSIONS.NOTICE_READ
  ],
  HR: [
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.NOTICE_READ,
    PERMISSIONS.NOTICE_CREATE,
    PERMISSIONS.NOTICE_UPDATE,
    // Phase-W2 C3 결정(B안): HR 도 지식 그래프 열람 허용
    PERMISSIONS.GRAPH_READ
  ],
  VIEWER: [
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.ADDITIONAL_DEV_READ,
    PERMISSIONS.GRAPH_READ,
    PERMISSIONS.NOTICE_READ
  ]
};
