CREATE TABLE "sales_contract" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"legacy_enter_cd" varchar(10),
	"legacy_cont_year" varchar(4),
	"legacy_cont_no" varchar(30),
	"company_type" varchar(10),
	"company_cd" varchar(10),
	"company_grp_nm" varchar(200),
	"company_nm" varchar(200),
	"company_no" varchar(40),
	"customer_no" varchar(20),
	"customer_email" varchar(400),
	"cust_nm" varchar(200),
	"cont_nm" varchar(200),
	"cont_gb_cd" varchar(10),
	"cont_ymd" varchar(8),
	"cont_symd" varchar(8),
	"cont_eymd" varchar(8),
	"main_cont_type" varchar(10),
	"new_yn" varchar(1),
	"in_out_type" varchar(10),
	"start_amt" numeric,
	"start_amt_rate" numeric(5, 2),
	"interim_amt_1" numeric,
	"interim_amt_rate_1" numeric(5, 2),
	"interim_amt_2" numeric,
	"interim_amt_rate_2" numeric(5, 2),
	"interim_amt_3" numeric,
	"interim_amt_rate_3" numeric(5, 2),
	"interim_amt_4" numeric,
	"interim_amt_rate_4" numeric(5, 2),
	"interim_amt_5" numeric,
	"interim_amt_rate_5" numeric(5, 2),
	"remain_amt" numeric,
	"remain_amt_rate" numeric(5, 2),
	"cont_impl_yn" varchar(1),
	"cont_publ_yn" varchar(1),
	"cont_grt_rate" numeric(5, 2),
	"advan_impl_yn" varchar(1),
	"advan_publ_yn" varchar(1),
	"advan_grt_rate" numeric(5, 2),
	"defect_impl_yn" varchar(1),
	"defect_publ_yn" varchar(1),
	"defect_grt_rate" numeric(5, 2),
	"defect_eymd" varchar(8),
	"inspec_conf_ymd" varchar(8),
	"start_amt_plan_ymd" varchar(8),
	"start_amt_publ_yn" varchar(1),
	"interim_amt_plan_ymd_1" varchar(8),
	"interim_amt_publ_yn_1" varchar(1),
	"interim_amt_plan_ymd_2" varchar(8),
	"interim_amt_publ_yn_2" varchar(1),
	"interim_amt_plan_ymd_3" varchar(8),
	"interim_amt_publ_yn_3" varchar(1),
	"interim_amt_plan_ymd_4" varchar(8),
	"interim_amt_publ_yn_4" varchar(1),
	"interim_amt_plan_ymd_5" varchar(8),
	"interim_amt_publ_yn_5" varchar(1),
	"remain_amt_plan_ymd" varchar(8),
	"remain_amt_publ_yn" varchar(1),
	"bef_cont_no" varchar(30),
	"cont_cancel_yn" varchar(1),
	"cont_init_yn" varchar(1),
	"file_seq" integer,
	"doc_no" varchar(200),
	"company_addr" varchar(1000),
	"company_oner" varchar(200),
	"suc_prob" varchar(10),
	"memo" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"created_by" uuid,
	"updated_by" uuid
);
--> statement-breakpoint
CREATE TABLE "sales_contract_addinfo" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"contract_id" uuid NOT NULL,
	"legacy_enter_cd" varchar(10),
	"legacy_cont_no" varchar(30),
	"legacy_sabun" varchar(13),
	"mail_id" varchar(100),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"created_by" uuid,
	"updated_by" uuid
);
--> statement-breakpoint
CREATE TABLE "sales_contract_month" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"contract_id" uuid NOT NULL,
	"legacy_cont_year" varchar(4),
	"legacy_cont_no" varchar(30),
	"legacy_seq" integer,
	"legacy_ym" varchar(6),
	"ym" varchar(6) NOT NULL,
	"bill_target_yn" varchar(1),
	"plan_in_man_month" numeric(15, 10),
	"plan_out_man_month" numeric(15, 10),
	"plan_serv_sale_amt" numeric,
	"plan_prod_sale_amt" numeric,
	"plan_inf_sale_amt" numeric,
	"plan_serv_in_cost_amt" numeric,
	"plan_serv_out_cost_amt" numeric,
	"plan_prod_cost_amt" numeric,
	"plan_in_cost_amt" numeric,
	"plan_out_cost_amt" numeric,
	"plan_indirect_grp_amt" numeric,
	"plan_indirect_com_amt" numeric,
	"plan_rent_amt" numeric,
	"plan_sga_amt" numeric,
	"plan_exp_amt" numeric,
	"view_in_man_month" numeric(15, 10),
	"view_out_man_month" numeric(15, 10),
	"view_serv_sale_amt" numeric,
	"view_prod_sale_amt" numeric,
	"view_inf_sale_amt" numeric,
	"view_serv_in_cost_amt" numeric,
	"view_serv_out_cost_amt" numeric,
	"view_prod_cost_amt" numeric,
	"view_in_cost_amt" numeric,
	"view_out_cost_amt" numeric,
	"view_indirect_grp_amt" numeric,
	"view_indirect_com_amt" numeric,
	"view_rent_amt" numeric,
	"view_sga_amt" numeric,
	"view_exp_amt" numeric,
	"perf_in_man_month" numeric(15, 10),
	"perf_out_man_month" numeric(15, 10),
	"perf_serv_sale_amt" numeric,
	"perf_prod_sale_amt" numeric,
	"perf_inf_sale_amt" numeric,
	"perf_serv_in_cost_amt" numeric,
	"perf_serv_out_cost_amt" numeric,
	"perf_prod_cost_amt" numeric,
	"perf_in_cost_amt" numeric,
	"perf_out_cost_amt" numeric,
	"perf_indirect_grp_amt" numeric,
	"perf_indirect_com_amt" numeric,
	"perf_rent_amt" numeric,
	"perf_sga_amt" numeric,
	"perf_exp_amt" numeric,
	"tax_order_amt" numeric,
	"tax_serv_amt" numeric,
	"rfc_end_yn" varchar(1) DEFAULT 'N',
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"created_by" uuid,
	"updated_by" uuid
);
--> statement-breakpoint
CREATE TABLE "sales_contract_service" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"legacy_enter_cd" varchar(10),
	"legacy_symd" varchar(8),
	"legacy_serv_sabun" varchar(20),
	"serv_sabun" varchar(20) NOT NULL,
	"serv_name" varchar(100),
	"bir_ymd" varchar(8),
	"symd" varchar(8),
	"eymd" varchar(8),
	"cpy_gb_cd" varchar(20),
	"cpy_name" varchar(200),
	"econt_amt" numeric,
	"econt_cnt" varchar(20),
	"job" varchar(200),
	"tel" varchar(50),
	"mail" varchar(50),
	"addr" varchar(500),
	"attend_cd" varchar(10),
	"skill_cd" varchar(10),
	"cmmnc_cd" varchar(10),
	"rspons_cd" varchar(10),
	"memo1" varchar(4000),
	"memo2" varchar(4000),
	"memo3" varchar(4000),
	"org_cd" varchar(10),
	"manager" varchar(13),
	"pjt_cd" varchar(20),
	"pjt_nm" varchar(300),
	"etc1" varchar(100),
	"etc2" varchar(100),
	"etc3" varchar(100),
	"etc4" varchar(100),
	"etc5" varchar(100),
	"etc6" varchar(100),
	"etc7" varchar(100),
	"etc8" varchar(100),
	"etc9" varchar(100),
	"etc10" varchar(100),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"created_by" uuid,
	"updated_by" uuid
);
--> statement-breakpoint
ALTER TABLE "sales_contract_addinfo" ADD CONSTRAINT "sales_contract_addinfo_contract_id_sales_contract_id_fk" FOREIGN KEY ("contract_id") REFERENCES "public"."sales_contract"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sales_contract_month" ADD CONSTRAINT "sales_contract_month_contract_id_sales_contract_id_fk" FOREIGN KEY ("contract_id") REFERENCES "public"."sales_contract"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "sales_contract_ws_idx" ON "sales_contract" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "sales_contract_ws_cust_idx" ON "sales_contract" USING btree ("workspace_id","customer_no");--> statement-breakpoint
CREATE INDEX "sales_contract_ws_cont_ymd_idx" ON "sales_contract" USING btree ("workspace_id","cont_ymd");--> statement-breakpoint
CREATE UNIQUE INDEX "sales_contract_legacy_uniq" ON "sales_contract" USING btree ("workspace_id","legacy_enter_cd","legacy_cont_year","legacy_cont_no");--> statement-breakpoint
CREATE INDEX "sales_contract_addinfo_ws_idx" ON "sales_contract_addinfo" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "sales_contract_addinfo_contract_idx" ON "sales_contract_addinfo" USING btree ("contract_id");--> statement-breakpoint
CREATE UNIQUE INDEX "sales_contract_addinfo_legacy_uniq" ON "sales_contract_addinfo" USING btree ("workspace_id","legacy_enter_cd","legacy_cont_no","legacy_sabun");--> statement-breakpoint
CREATE INDEX "sales_contract_month_ws_idx" ON "sales_contract_month" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "sales_contract_month_contract_idx" ON "sales_contract_month" USING btree ("contract_id");--> statement-breakpoint
CREATE INDEX "sales_contract_month_contract_ym_idx" ON "sales_contract_month" USING btree ("contract_id","ym");--> statement-breakpoint
CREATE INDEX "sales_contract_service_ws_idx" ON "sales_contract_service" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "sales_contract_service_ws_serv_sabun_idx" ON "sales_contract_service" USING btree ("workspace_id","serv_sabun");--> statement-breakpoint
CREATE INDEX "sales_contract_service_ws_pjt_idx" ON "sales_contract_service" USING btree ("workspace_id","pjt_cd");