CREATE TABLE "sales_contract_upload" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"legacy_enter_cd" varchar(10),
	"ym" varchar(6) NOT NULL,
	"in_out_type" varchar(10),
	"cost_cd" varchar(20) NOT NULL,
	"cost_grp_nm" varchar(200),
	"cost_nm" varchar(200),
	"product_type" varchar(20) NOT NULL,
	"cont_type" varchar(20) NOT NULL,
	"company_cd" varchar(50) NOT NULL,
	"company_nm" varchar(300),
	"pjt_code" varchar(50) NOT NULL,
	"pjt_nm" varchar(300),
	"suc_prob" varchar(10),
	"plan_serv_sale_amt" numeric,
	"plan_prod_sale_amt" numeric,
	"plan_inf_sale_amt" numeric,
	"plan_serv_out_cost_amt" numeric,
	"plan_prod_cost_amt" numeric,
	"plan_rent_amt" numeric,
	"plan_exp_amt" numeric,
	"plan_sga_amt" numeric,
	"plan_in_cost_amt" numeric,
	"plan_out_cost_amt" numeric,
	"plan_indirect_grp_amt" numeric,
	"plan_indirect_com_amt" numeric,
	"plan_in_man_month" numeric(15, 10),
	"plan_out_man_month" numeric(15, 10),
	"view_serv_sale_amt" numeric,
	"view_prod_sale_amt" numeric,
	"view_inf_sale_amt" numeric,
	"view_serv_out_cost_amt" numeric,
	"view_prod_cost_amt" numeric,
	"view_rent_amt" numeric,
	"view_exp_amt" numeric,
	"view_sga_amt" numeric,
	"view_in_cost_amt" numeric,
	"view_out_cost_amt" numeric,
	"view_indirect_grp_amt" numeric,
	"view_indirect_com_amt" numeric,
	"view_in_man_month" numeric(15, 10),
	"view_out_man_month" numeric(15, 10),
	"perf_serv_sale_amt" numeric,
	"perf_prod_sale_amt" numeric,
	"perf_inf_sale_amt" numeric,
	"perf_serv_out_cost_amt" numeric,
	"perf_prod_cost_amt" numeric,
	"perf_rent_amt" numeric,
	"perf_exp_amt" numeric,
	"perf_sga_amt" numeric,
	"perf_in_cost_amt" numeric,
	"perf_out_cost_amt" numeric,
	"perf_indirect_grp_amt" numeric,
	"perf_indirect_com_amt" numeric,
	"perf_in_man_month" numeric(15, 10),
	"perf_out_man_month" numeric(15, 10),
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"created_by" uuid,
	"updated_by" uuid
);
--> statement-breakpoint
CREATE TABLE "sales_plan_acl" (
	"plan_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"can_read" boolean DEFAULT true NOT NULL,
	"can_write" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "sales_plan_acl_plan_id_user_id_pk" PRIMARY KEY("plan_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "sales_plan_view_performance" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"legacy_enter_cd" varchar(10),
	"data_type" varchar(20) NOT NULL,
	"company_cd" varchar(50) NOT NULL,
	"cost_cd" varchar(20) NOT NULL,
	"pjt_code" varchar(50) NOT NULL,
	"cont_year" varchar(4) NOT NULL,
	"pjt_nm" varchar(300),
	"company_no" varchar(40),
	"company_nm" varchar(300),
	"company_type" varchar(20),
	"in_out_type" varchar(10),
	"title" varchar(300),
	"cust_nm" varchar(200),
	"cont_gb_cd" varchar(20),
	"cont_ymd" varchar(8),
	"cont_symd" varchar(8),
	"cont_eymd" varchar(8),
	"new_yn" varchar(1),
	"cont_type" varchar(20),
	"product_type" varchar(20),
	"tot_order_amt" numeric,
	"ser_order_amt" numeric,
	"prd_order_amt" numeric,
	"inf_order_amt" numeric,
	"serv_amt" numeric,
	"prod_amt" numeric,
	"in_man_month" numeric(15, 10),
	"out_man_month" numeric(15, 10),
	"sga_amt" numeric,
	"exp_amt" numeric,
	"change_reason" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"created_by" uuid,
	"updated_by" uuid
);
--> statement-breakpoint
CREATE TABLE "sales_plan_view_performance_month" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"plan_id" uuid NOT NULL,
	"ym" varchar(6) NOT NULL,
	"ser_order_amt" numeric,
	"prd_order_amt" numeric,
	"inf_order_amt" numeric,
	"serv_amt" numeric,
	"prod_amt" numeric,
	"in_man_month" numeric(15, 10),
	"out_man_month" numeric(15, 10),
	"dir_in_amt" numeric,
	"dir_out_amt" numeric,
	"indir_org_amt" numeric,
	"indir_all_amt" numeric,
	"sga_amt" numeric,
	"exp_amt" numeric,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"created_by" uuid,
	"updated_by" uuid
);
--> statement-breakpoint
ALTER TABLE "sales_plan_acl" ADD CONSTRAINT "sales_plan_acl_plan_id_sales_plan_view_performance_id_fk" FOREIGN KEY ("plan_id") REFERENCES "public"."sales_plan_view_performance"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sales_plan_acl" ADD CONSTRAINT "sales_plan_acl_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sales_plan_view_performance_month" ADD CONSTRAINT "sales_plan_view_performance_month_plan_id_sales_plan_view_performance_id_fk" FOREIGN KEY ("plan_id") REFERENCES "public"."sales_plan_view_performance"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "sales_contract_upload_ws_ym_idx" ON "sales_contract_upload" USING btree ("workspace_id","ym");--> statement-breakpoint
CREATE INDEX "sales_contract_upload_ws_company_idx" ON "sales_contract_upload" USING btree ("workspace_id","company_cd");--> statement-breakpoint
CREATE UNIQUE INDEX "sales_contract_upload_legacy_uniq" ON "sales_contract_upload" USING btree ("workspace_id","ym","cost_cd","company_cd","product_type","cont_type","pjt_code");--> statement-breakpoint
CREATE INDEX "sales_plan_view_perf_ws_year_idx" ON "sales_plan_view_performance" USING btree ("workspace_id","cont_year");--> statement-breakpoint
CREATE INDEX "sales_plan_view_perf_ws_company_idx" ON "sales_plan_view_performance" USING btree ("workspace_id","company_cd");--> statement-breakpoint
CREATE UNIQUE INDEX "sales_plan_view_perf_legacy_uniq" ON "sales_plan_view_performance" USING btree ("workspace_id","data_type","company_cd","cost_cd","pjt_code","cont_year");--> statement-breakpoint
CREATE UNIQUE INDEX "sales_plan_view_perf_month_plan_ym_uniq" ON "sales_plan_view_performance_month" USING btree ("plan_id","ym");--> statement-breakpoint
CREATE INDEX "sales_plan_view_perf_month_ws_ym_idx" ON "sales_plan_view_performance_month" USING btree ("workspace_id","ym");