/**
 * Phase-W0 Bootstrap
 *
 * Reads docs/canonical/*.md and initializes wiki/{workspaceId}/auto/ with one
 * wiki page per canonical section. Unlike normal ingest:
 *  - 1 source → 1 page is allowed (multi-page update is NOT enforced)
 *  - frontmatter is generated by a lightweight LLM call (analysis prompt)
 *  - aliases must have ≥3 entries (ingest_dlq if < 3)
 *  - writes to wiki/{workspaceId}/auto/concepts/{slug}.md
 *
 * Usage: WORKSPACE_ID=xxx pnpm wiki:bootstrap [--dry-run]
 */

import "dotenv/config";
import { promises as fs } from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

import { db } from "@jarvis/db/client";
import { wikiPageIndex } from "@jarvis/db/schema/wiki-page-index";
import {
  GitRepo,
  defaultBotAuthor,
  serializeFrontmatter,
  defaultFrontmatter,
  splitFrontmatter,
  parseFrontmatter,
  exists,
} from "@jarvis/wiki-fs";
import {
  buildAnalysisPrompt,
  buildGenerationPrompt,
  parseFileBlocks,
  MIN_ALIASES,
  MAX_SOURCE_CHARS,
  TRUNCATION_MARKER,
} from "@jarvis/wiki-agent";
import type { AnalysisResult } from "@jarvis/wiki-agent";
import OpenAI from "openai";

// ── Config ────────────────────────────────────────────────────────────────────

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "../../../../");
const CANONICAL_DIR = path.join(REPO_ROOT, "docs", "canonical");

const WORKSPACE_ID = process.env["WORKSPACE_ID"] ?? "";
const DRY_RUN = process.argv.includes("--dry-run");
const BOOTSTRAP_MODEL = process.env["BOOTSTRAP_AI_MODEL"] ?? "gpt-5.4-mini";

// ── Types ─────────────────────────────────────────────────────────────────────

interface CanonicalDoc {
  slug: string;
  filePath: string;
  rawContent: string;
  /** Extracted from the canonical frontmatter `section` field */
  sectionTitle: string;
}

interface BootstrapPage {
  slug: string;
  wikiRelPath: string;
  content: string;
  title: string;
  aliases: string[];
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function extractSlugFromFilename(filename: string): string {
  // e.g. "001-hr-reform-overview.md" → "hr-reform-overview"
  return filename.replace(/^\d+-/, "").replace(/\.md$/, "");
}

function extractSectionTitle(raw: string): string {
  // Read the `section:` field from the canonical frontmatter stub
  const { frontmatter } = splitFrontmatter(raw);
  if (!frontmatter) return "";
  const match = frontmatter.match(/^section:\s*"(.+)"/m);
  return match?.[1] ?? "";
}

function truncateSource(text: string): string {
  if (text.length <= MAX_SOURCE_CHARS) return text;
  return text.slice(0, MAX_SOURCE_CHARS) + TRUNCATION_MARKER;
}

async function readCanonicalDocs(): Promise<CanonicalDoc[]> {
  const entries = await fs.readdir(CANONICAL_DIR);
  const mdFiles = entries.filter((e) => e.endsWith(".md")).sort();

  const docs: CanonicalDoc[] = [];
  for (const filename of mdFiles) {
    const filePath = path.join(CANONICAL_DIR, filename);
    const rawContent = await fs.readFile(filePath, "utf-8");
    const slug = extractSlugFromFilename(filename);
    const sectionTitle = extractSectionTitle(rawContent);
    docs.push({ slug, filePath, rawContent, sectionTitle });
  }
  return docs;
}

// ── LLM call (skipped in dry-run) ────────────────────────────────────────────

async function generateWikiPage(
  openai: OpenAI,
  doc: CanonicalDoc,
): Promise<BootstrapPage> {
  const sourceText = truncateSource(doc.rawContent);

  // Step A — Analysis
  const analysisMessages = buildAnalysisPrompt({
    source: sourceText,
    existingPages: [],
    folderContext: "auto/concepts",
    sourceFileName: path.basename(doc.filePath),
  });

  const analysisResponse = await openai.chat.completions.create({
    model: BOOTSTRAP_MODEL,
    messages: analysisMessages,
    response_format: { type: "json_object" },
  });

  const analysisJson = analysisResponse.choices[0]?.message?.content ?? "{}";
  const analysis = JSON.parse(analysisJson) as AnalysisResult;

  // Step B — Generation
  const generationMessages = buildGenerationPrompt({
    source: sourceText,
    analysis,
    existingPages: [],
    folderContext: "auto/concepts",
    sourceFileName: path.basename(doc.filePath),
  });

  const generationResponse = await openai.chat.completions.create({
    model: BOOTSTRAP_MODEL,
    messages: generationMessages,
  });

  const generationText =
    generationResponse.choices[0]?.message?.content ?? "";

  // Parse <file> blocks from Step B output
  const fileBlocks = parseFileBlocks(generationText);
  const primary = fileBlocks[0];

  if (!primary) {
    throw new Error(
      `[bootstrap] No file block generated for slug=${doc.slug}`,
    );
  }

  // Extract aliases from generated frontmatter
  const { data: fm } = parseFrontmatter(primary.content);

  const aliases = fm.aliases ?? [];
  if (aliases.length < MIN_ALIASES) {
    throw new Error(
      `[ingest_dlq] slug=${doc.slug} has ${aliases.length} aliases < MIN_ALIASES(${MIN_ALIASES})`,
    );
  }

  const wikiRelPath = `wiki/${WORKSPACE_ID}/auto/concepts/${doc.slug}.md`;
  return {
    slug: doc.slug,
    wikiRelPath,
    content: primary.content,
    title: fm.title || doc.sectionTitle,
    aliases,
  };
}

// ── Dry-run stub ──────────────────────────────────────────────────────────────

function makeDryRunPage(doc: CanonicalDoc): BootstrapPage {
  const now = new Date().toISOString();
  const fm = {
    ...defaultFrontmatter(),
    title: doc.sectionTitle || doc.slug,
    type: "concept" as const,
    workspaceId: WORKSPACE_ID || "dry-run-workspace",
    sensitivity: "INTERNAL" as const,
    requiredPermission: "knowledge:read",
    sources: [`docs/canonical/${path.basename(doc.filePath)}`],
    aliases: [
      doc.sectionTitle,
      doc.slug,
      doc.slug.replace(/-/g, " "),
    ].filter(Boolean),
    tags: ["bootstrap", "canonical"],
    created: now,
    updated: now,
    authority: "auto" as const,
    linkedPages: [],
  };

  const body = `\n${doc.rawContent.trim()}\n`;
  const content = serializeFrontmatter(fm, body);

  return {
    slug: doc.slug,
    wikiRelPath: `wiki/${WORKSPACE_ID || "dry-run-workspace"}/auto/concepts/${doc.slug}.md`,
    content,
    title: fm.title,
    aliases: fm.aliases,
  };
}

// ── Index / Log generation ────────────────────────────────────────────────────

function buildIndexMd(pages: BootstrapPage[], workspaceId: string): string {
  const now = new Date().toISOString();
  const lines = [
    `# Wiki Index — ${workspaceId}`,
    "",
    `_Bootstrap generated: ${now}_`,
    "",
    "## Pages",
    "",
    ...pages.map(
      (p) => `- [[auto/concepts/${p.slug}|${p.title}]]`,
    ),
    "",
  ];
  return lines.join("\n");
}

function buildLogMd(pages: BootstrapPage[], workspaceId: string): string {
  const now = new Date().toISOString();
  const lines = [
    `# Bootstrap Log — ${workspaceId}`,
    "",
    `- **timestamp**: ${now}`,
    `- **pages**: ${pages.length}`,
    `- **source**: docs/canonical/`,
    "",
    "## Created pages",
    "",
    ...pages.map(
      (p, i) => `${String(i + 1).padStart(3, "0")}. \`${p.wikiRelPath}\``,
    ),
    "",
  ];
  return lines.join("\n");
}

// ── DB projection ─────────────────────────────────────────────────────────────

async function upsertPageIndex(
  page: BootstrapPage,
  gitSha: string,
  workspaceId: string,
): Promise<void> {
  const { data: fm } = parseFrontmatter(page.content);

  await db
    .insert(wikiPageIndex)
    .values({
      workspaceId,
      path: page.wikiRelPath,
      title: page.title,
      slug: page.slug,
      type: fm.type ?? "concept",
      authority: fm.authority ?? "auto",
      sensitivity: fm.sensitivity ?? "INTERNAL",
      requiredPermission: fm.requiredPermission ?? "knowledge:read",
      frontmatter: fm as Record<string, unknown>,
      gitSha,
      stale: false,
      publishedStatus: "draft",
      freshnessSlaDays: typeof fm.freshnessSlaDays === "number" ? fm.freshnessSlaDays : null,
    })
    .onConflictDoUpdate({
      target: [wikiPageIndex.workspaceId, wikiPageIndex.path],
      set: {
        title: page.title,
        slug: page.slug,
        frontmatter: fm as Record<string, unknown>,
        gitSha,
        stale: false,
        freshnessSlaDays: typeof fm.freshnessSlaDays === "number" ? fm.freshnessSlaDays : null,
        updatedAt: new Date(),
      },
    });
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  if (!DRY_RUN && !WORKSPACE_ID) {
    console.error("Error: WORKSPACE_ID env var is required (or use --dry-run)");
    process.exit(1);
  }

  const workspaceId = WORKSPACE_ID || "dry-run-workspace";

  console.log(`[wiki-bootstrap] mode=${DRY_RUN ? "dry-run" : "live"}`);
  console.log(`[wiki-bootstrap] workspaceId=${workspaceId}`);
  console.log(`[wiki-bootstrap] canonical=${CANONICAL_DIR}`);

  // 1. Read canonical docs
  const docs = await readCanonicalDocs();
  console.log(`[wiki-bootstrap] found ${docs.length} canonical docs`);

  // 2. Set up OpenAI (only in live mode)
  const openai = DRY_RUN
    ? null
    : new OpenAI({ apiKey: process.env["OPENAI_API_KEY"] });

  // 3. Generate wiki pages
  const pages: BootstrapPage[] = [];
  for (const doc of docs) {
    console.log(`[wiki-bootstrap] processing ${doc.slug}...`);
    try {
      const page = DRY_RUN
        ? makeDryRunPage(doc)
        : await generateWikiPage(openai!, doc);
      pages.push(page);
      if (DRY_RUN) {
        console.log(
          `  [dry-run] would write: ${page.wikiRelPath} (aliases: ${page.aliases.join(", ")})`,
        );
      }
    } catch (err) {
      console.error(`  [error] ${doc.slug}: ${String(err)}`);
      // Route to ingest_dlq equivalent: log and continue
    }
  }

  if (DRY_RUN) {
    console.log(
      `\n[wiki-bootstrap] dry-run complete — ${pages.length} pages would be created.`,
    );
    return;
  }

  // 4. Write + commit via GitRepo
  const indexPath = `wiki/${workspaceId}/index.md`;
  const logPath = `wiki/${workspaceId}/log.md`;

  const files: Record<string, string> = {};
  for (const page of pages) {
    files[page.wikiRelPath] = page.content;
  }
  files[indexPath] = buildIndexMd(pages, workspaceId);
  files[logPath] = buildLogMd(pages, workspaceId);

  // Initialize repo if needed
  const gitRepoPath = path.join(REPO_ROOT, "wiki", workspaceId);
  const git = new GitRepo(gitRepoPath);

  const hasGit = await exists(path.join(gitRepoPath, ".git"));
  if (!hasGit) {
    console.log("[wiki-bootstrap] initializing git repo...");
    await git.createRepo("main");
  }

  const author = defaultBotAuthor();
  const commitMessage = `[ingest] Phase-W0 bootstrap — ${pages.length} canonical pages`;

  // Convert absolute paths to repo-relative for GitRepo
  const repoRelativeFiles: Record<string, string> = {};
  for (const [absOrRel, content] of Object.entries(files)) {
    // wikiRelPath is already repo-relative (wiki/workspaceId/...)
    repoRelativeFiles[absOrRel] = content;
  }

  console.log("[wiki-bootstrap] committing pages...");
  const commitInfo = await git.writeAndCommit({
    files: repoRelativeFiles,
    message: commitMessage,
    author,
  });
  console.log(`[wiki-bootstrap] committed: ${commitInfo.sha}`);

  // 5. DB projection
  console.log("[wiki-bootstrap] updating wiki_page_index...");
  for (const page of pages) {
    await upsertPageIndex(page, commitInfo.sha, workspaceId);
  }
  console.log(`[wiki-bootstrap] done — ${pages.length} pages indexed.`);
}

main().catch((err) => {
  console.error("[wiki-bootstrap] fatal:", err);
  process.exit(1);
});
