"use client";

/**
 * WikiEditor — Tiptap-based markdown editor for `wiki/manual/**` pages.
 * ----------------------------------------------------------------------------
 * Owns:
 *   - Frontmatter panel (delegates to <FrontmatterPanel />)
 *   - Toolbar of formatting commands
 *   - Tiptap <EditorContent /> with markdown round-tripping
 *   - `[[wikilink]]` autocomplete dropdown (currently mock data)
 *
 * Karpathy-first reminder: this component must NOT be wired up against
 * `wiki/auto/**` paths. The auto tree is regenerated by the LLM pipeline.
 */
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useTranslations } from "next-intl";
import { useEditor, EditorContent, type Editor } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import Link from "@tiptap/extension-link";
import CodeBlockLowlight from "@tiptap/extension-code-block-lowlight";
import { Markdown } from "tiptap-markdown";
import { common, createLowlight } from "lowlight";
import { Input } from "@/components/ui/input";
import { Toolbar, type ToolbarFeature } from "@/components/RichTextEditor";
import { FrontmatterPanel, type Frontmatter } from "./FrontmatterPanel";
import { WikiLinkExtension } from "./extensions/WikiLinkExtension";

const WIKI_TOOLBAR_FEATURES: ToolbarFeature[] = [
  "bold",
  "italic",
  "link",
  "heading",
  "list",
  "codeBlock",
];

const lowlight = createLowlight(common);

interface WikiEditorProps {
  initialContent: string;
  onChange: (markdown: string, frontmatter: Frontmatter) => void;
  pageSlug?: string;
  workspaceId: string;
  readOnly?: boolean;
}

interface FrontmatterParseResult {
  frontmatter: Frontmatter;
  body: string;
}

/** Pulls a `---\n...\n---` frontmatter block off the top of a markdown string. */
function splitFrontmatter(input: string): FrontmatterParseResult {
  const match = input.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) {
    return { frontmatter: { title: "" }, body: input };
  }
  const [, raw, body] = match;
  const fm: Frontmatter = { title: "" };
  for (const line of (raw ?? "").split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const sepIdx = trimmed.indexOf(":");
    if (sepIdx === -1) continue;
    const key = trimmed.slice(0, sepIdx).trim();
    const value = trimmed.slice(sepIdx + 1).trim();
    if (!key) continue;
    if (key === "tags") {
      // Accept JSON array or comma-separated.
      try {
        const parsed = JSON.parse(value);
        if (Array.isArray(parsed)) {
          fm.tags = parsed.map(String);
          continue;
        }
      } catch {
        // fallthrough
      }
      fm.tags = value
        .replace(/^\[|\]$/g, "")
        .split(",")
        .map((s) => s.trim().replace(/^["']|["']$/g, ""))
        .filter(Boolean);
      continue;
    }
    if (key === "title") {
      fm.title = value.replace(/^["']|["']$/g, "");
      continue;
    }
    if (key === "sensitivity") {
      const cleaned = value.replace(/^["']|["']$/g, "");
      if (cleaned === "public" || cleaned === "internal" || cleaned === "restricted" || cleaned === "secret") {
        fm.sensitivity = cleaned;
      }
      continue;
    }
    try {
      fm[key] = JSON.parse(value);
    } catch {
      fm[key] = value.replace(/^["']|["']$/g, "");
    }
  }
  return { frontmatter: fm, body: body ?? "" };
}

/**
 * `tiptap-markdown` injects a `markdown` storage slot at runtime but does not
 * augment the Editor's TS types, so we read it through a narrow cast.
 */
function getMarkdownFromEditor(ed: Editor): string {
  const storage = ed.storage as unknown as Record<string, unknown>;
  const slot = storage.markdown as { getMarkdown?: () => string } | undefined;
  return slot?.getMarkdown?.() ?? "";
}

function serializeFrontmatter(fm: Frontmatter): string {
  const entries = Object.entries(fm).filter(([, v]) => v !== undefined && v !== null);
  if (entries.length === 0) return "";
  const lines = entries.map(([k, v]) => {
    if (Array.isArray(v)) return `${k}: [${v.map((s) => JSON.stringify(s)).join(", ")}]`;
    if (typeof v === "string") return `${k}: ${v}`;
    return `${k}: ${JSON.stringify(v)}`;
  });
  return `---\n${lines.join("\n")}\n---\n\n`;
}

interface SuggestState {
  open: boolean;
  query: string;
  position: { top: number; left: number } | null;
}

interface WikiSearchPage {
  slug: string;
  title: string;
  path: string;
}

type SuggestFetchState =
  | { state: "idle"; pages: WikiSearchPage[] }
  | { state: "loading"; pages: WikiSearchPage[] }
  | { state: "error"; pages: WikiSearchPage[] };

export function WikiEditor({
  initialContent,
  onChange,
  pageSlug: _pageSlug,
  workspaceId,
  readOnly = false,
}: WikiEditorProps) {
  const t = useTranslations("WikiEditor");
  const tWikilink = useTranslations("WikiEditor.wikilink");

  const parsed = useMemo(() => splitFrontmatter(initialContent), [initialContent]);
  const [frontmatter, setFrontmatter] = useState<Frontmatter>(parsed.frontmatter);
  const frontmatterRef = useRef<Frontmatter>(parsed.frontmatter);
  useEffect(() => {
    frontmatterRef.current = frontmatter;
  }, [frontmatter]);

  const [suggest, setSuggest] = useState<SuggestState>({
    open: false,
    query: "",
    position: null,
  });
  const editorContainerRef = useRef<HTMLDivElement>(null);

  const editor = useEditor({
    extensions: [
      StarterKit.configure({
        codeBlock: false, // Replaced by CodeBlockLowlight below.
      }),
      Link.configure({
        openOnClick: false,
        autolink: true,
        HTMLAttributes: { class: "text-blue-600 underline" },
      }),
      CodeBlockLowlight.configure({ lowlight }),
      Markdown.configure({
        html: false,
        linkify: true,
        breaks: false,
        transformPastedText: true,
      }),
      WikiLinkExtension.configure({ workspaceId, HTMLAttributes: {} }),
    ],
    content: parsed.body,
    editable: !readOnly,
    immediatelyRender: false,
    editorProps: {
      attributes: {
        class:
          "prose prose-sm max-w-none min-h-[400px] px-4 py-3 focus:outline-none",
        "data-testid": "tiptap-editor",
      },
    },
    onUpdate: ({ editor: ed }) => {
      const md = getMarkdownFromEditor(ed);
      const full = serializeFrontmatter(frontmatterRef.current) + md;
      onChange(full, frontmatterRef.current);
    },
  });

  // Surface frontmatter changes back to the parent without round-tripping
  // through the editor.
  const handleFrontmatterChange = useCallback(
    (next: Frontmatter) => {
      setFrontmatter(next);
      frontmatterRef.current = next;
      const md = editor ? getMarkdownFromEditor(editor) : "";
      onChange(serializeFrontmatter(next) + md, next);
    },
    [editor, onChange],
  );

  // Listen for the WikiLinkExtension's `[[` signal and open the dropdown
  // anchored to the current selection.
  useEffect(() => {
    if (!editor) return;
    function onSuggest(_e: Event) {
      if (!editor) return;
      const { from } = editor.state.selection;
      const coords = editor.view.coordsAtPos(from);
      const containerRect = editorContainerRef.current?.getBoundingClientRect();
      const top = containerRect ? coords.bottom - containerRect.top + 4 : coords.bottom;
      const left = containerRect ? coords.left - containerRect.left : coords.left;
      setSuggest({ open: true, query: "", position: { top, left } });
    }
    window.addEventListener("showWikiLinkSuggest", onSuggest);
    return () => window.removeEventListener("showWikiLinkSuggest", onSuggest);
  }, [editor]);

  // Phase-W2: 자동완성을 GET /api/wiki/search 로 교체. AbortController + 150ms debounce.
  const [fetchState, setFetchState] = useState<SuggestFetchState>({
    state: "idle",
    pages: [],
  });

  useEffect(() => {
    if (!suggest.open) return;
    const controller = new AbortController();
    const timer = setTimeout(() => {
      const params = new URLSearchParams({
        workspaceId,
        q: suggest.query,
        limit: "6",
      });
      setFetchState((prev) => ({ state: "loading", pages: prev.pages }));
      fetch(`/api/wiki/search?${params.toString()}`, {
        signal: controller.signal,
        credentials: "same-origin",
      })
        .then((res) => {
          if (!res.ok) throw new Error(`HTTP ${res.status}`);
          return res.json() as Promise<{ pages: WikiSearchPage[] }>;
        })
        .then((data) => {
          setFetchState({ state: "idle", pages: data.pages ?? [] });
        })
        .catch((err: unknown) => {
          if ((err as { name?: string })?.name === "AbortError") return;
          setFetchState((prev) => ({ state: "error", pages: prev.pages }));
        });
    }, 150);
    return () => {
      controller.abort();
      clearTimeout(timer);
    };
  }, [suggest.open, suggest.query, workspaceId]);

  const filteredPages = fetchState.pages;
  const isLoading = fetchState.state === "loading";
  const isErrored = fetchState.state === "error";

  const insertWikiLink = (slug: string, title: string) => {
    if (!editor) return;
    editor
      .chain()
      .focus()
      .insertContent({
        type: "text",
        text: title,
        marks: [
          {
            type: "wikiLink",
            attrs: { href: slug, label: title },
          },
        ],
      })
      .run();
    setSuggest({ open: false, query: "", position: null });
  };

  const closeSuggest = () => setSuggest((s) => ({ ...s, open: false }));

  if (!editor) {
    // SSR placeholder — the dynamic-import wrapper in the page still renders this on first paint.
    return (
      <div className="rounded-lg border border-gray-200 bg-white p-6 text-sm text-gray-400">
        {t("loading")}
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <FrontmatterPanel
        frontmatter={frontmatter}
        onChange={handleFrontmatterChange}
        readOnly={readOnly}
      />

      <div className="rounded-lg border border-gray-200 bg-white">
        <Toolbar
          editor={editor}
          features={WIKI_TOOLBAR_FEATURES}
          readOnly={readOnly}
        />
        <div ref={editorContainerRef} className="relative">
          <EditorContent editor={editor} />

          {suggest.open && suggest.position && (
            <div
              data-testid="wikilink-autocomplete-dropdown"
              role="listbox"
              className="absolute z-30 w-72 rounded-lg border border-gray-200 bg-white shadow-lg"
              style={{ top: suggest.position.top, left: suggest.position.left }}
            >
              <div className="p-2 border-b border-gray-100">
                <Input
                  autoFocus
                  value={suggest.query}
                  placeholder={tWikilink("placeholder")}
                  onChange={(e) =>
                    setSuggest((s) => ({ ...s, query: e.target.value }))
                  }
                  onKeyDown={(e) => {
                    if (e.key === "Escape") {
                      e.preventDefault();
                      closeSuggest();
                    }
                  }}
                />
              </div>
              <ul className="max-h-60 overflow-auto py-1">
                {isLoading ? (
                  <li className="px-3 py-2 text-sm text-gray-400">
                    {tWikilink("searching")}
                  </li>
                ) : isErrored ? (
                  <li className="px-3 py-2 text-sm text-red-600">
                    {tWikilink("searchFailed")}
                  </li>
                ) : filteredPages.length === 0 ? (
                  <li className="px-3 py-2 text-sm text-gray-400">
                    {tWikilink("noResults")}
                  </li>
                ) : (
                  filteredPages.map((p) => (
                    <li key={p.slug}>
                      <button
                        type="button"
                        onClick={() => insertWikiLink(p.slug, p.title)}
                        className="flex w-full items-start justify-between gap-2 px-3 py-2 text-left text-sm hover:bg-gray-50"
                      >
                        <span className="font-medium text-gray-900">{p.title}</span>
                        <span className="text-xs text-gray-400">{p.slug}</span>
                      </button>
                    </li>
                  ))
                )}
              </ul>
              <div className="border-t border-gray-100 px-3 py-1.5 text-right">
                <button
                  type="button"
                  onClick={closeSuggest}
                  className="text-xs text-gray-500 hover:text-gray-700"
                >
                  Esc
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

export default WikiEditor;
