"use client";

/**
 * WikiEditor — Tiptap-based markdown editor for `wiki/manual/**` pages.
 * ----------------------------------------------------------------------------
 * Owns:
 *   - Frontmatter panel (delegates to <FrontmatterPanel />)
 *   - Toolbar of formatting commands
 *   - Tiptap <EditorContent /> with markdown round-tripping
 *   - `[[wikilink]]` autocomplete dropdown (currently mock data)
 *
 * Karpathy-first reminder: this component must NOT be wired up against
 * `wiki/auto/**` paths. The auto tree is regenerated by the LLM pipeline.
 */
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useTranslations } from "next-intl";
import { useEditor, EditorContent, type Editor } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import Link from "@tiptap/extension-link";
import CodeBlockLowlight from "@tiptap/extension-code-block-lowlight";
import { Markdown } from "tiptap-markdown";
import { common, createLowlight } from "lowlight";
import {
  Bold,
  Italic,
  Link as LinkIcon,
  Code2,
  Heading1,
  Heading2,
  Heading3,
  List,
  ListOrdered,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { FrontmatterPanel, type Frontmatter } from "./FrontmatterPanel";
import { WikiLinkExtension } from "./extensions/WikiLinkExtension";

const lowlight = createLowlight(common);

interface WikiEditorProps {
  initialContent: string;
  onChange: (markdown: string, frontmatter: Frontmatter) => void;
  pageSlug?: string;
  workspaceId: string;
  readOnly?: boolean;
}

interface FrontmatterParseResult {
  frontmatter: Frontmatter;
  body: string;
}

/** Pulls a `---\n...\n---` frontmatter block off the top of a markdown string. */
function splitFrontmatter(input: string): FrontmatterParseResult {
  const match = input.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) {
    return { frontmatter: { title: "" }, body: input };
  }
  const [, raw, body] = match;
  const fm: Frontmatter = { title: "" };
  for (const line of (raw ?? "").split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const sepIdx = trimmed.indexOf(":");
    if (sepIdx === -1) continue;
    const key = trimmed.slice(0, sepIdx).trim();
    const value = trimmed.slice(sepIdx + 1).trim();
    if (!key) continue;
    if (key === "tags") {
      // Accept JSON array or comma-separated.
      try {
        const parsed = JSON.parse(value);
        if (Array.isArray(parsed)) {
          fm.tags = parsed.map(String);
          continue;
        }
      } catch {
        // fallthrough
      }
      fm.tags = value
        .replace(/^\[|\]$/g, "")
        .split(",")
        .map((s) => s.trim().replace(/^["']|["']$/g, ""))
        .filter(Boolean);
      continue;
    }
    if (key === "title") {
      fm.title = value.replace(/^["']|["']$/g, "");
      continue;
    }
    if (key === "sensitivity") {
      const cleaned = value.replace(/^["']|["']$/g, "");
      if (cleaned === "public" || cleaned === "internal" || cleaned === "confidential") {
        fm.sensitivity = cleaned;
      }
      continue;
    }
    try {
      fm[key] = JSON.parse(value);
    } catch {
      fm[key] = value.replace(/^["']|["']$/g, "");
    }
  }
  return { frontmatter: fm, body: body ?? "" };
}

/**
 * `tiptap-markdown` injects a `markdown` storage slot at runtime but does not
 * augment the Editor's TS types, so we read it through a narrow cast.
 */
function getMarkdownFromEditor(ed: Editor): string {
  const storage = ed.storage as unknown as Record<string, unknown>;
  const slot = storage.markdown as { getMarkdown?: () => string } | undefined;
  return slot?.getMarkdown?.() ?? "";
}

function serializeFrontmatter(fm: Frontmatter): string {
  const entries = Object.entries(fm).filter(([, v]) => v !== undefined && v !== null);
  if (entries.length === 0) return "";
  const lines = entries.map(([k, v]) => {
    if (Array.isArray(v)) return `${k}: [${v.map((s) => JSON.stringify(s)).join(", ")}]`;
    if (typeof v === "string") return `${k}: ${v}`;
    return `${k}: ${JSON.stringify(v)}`;
  });
  return `---\n${lines.join("\n")}\n---\n\n`;
}

// Mock until the page index API lands. Keep this list small and obviously fake
// so tests can match against deterministic strings.
const MOCK_PAGES: ReadonlyArray<{ slug: string; title: string }> = [
  { slug: "onboarding/welcome", title: "Welcome" },
  { slug: "onboarding/checklist", title: "Onboarding Checklist" },
  { slug: "hr/leave-policy", title: "Leave Policy" },
  { slug: "hr/expense-policy", title: "Expense Policy" },
  { slug: "engineering/runbooks", title: "Engineering Runbooks" },
  { slug: "engineering/release-process", title: "Release Process" },
  { slug: "security/incident-response", title: "Incident Response" },
];

interface SuggestState {
  open: boolean;
  query: string;
  position: { top: number; left: number } | null;
}

export function WikiEditor({
  initialContent,
  onChange,
  pageSlug: _pageSlug,
  workspaceId,
  readOnly = false,
}: WikiEditorProps) {
  const t = useTranslations("WikiEditor");
  const tToolbar = useTranslations("WikiEditor.toolbar");
  const tWikilink = useTranslations("WikiEditor.wikilink");

  const parsed = useMemo(() => splitFrontmatter(initialContent), [initialContent]);
  const [frontmatter, setFrontmatter] = useState<Frontmatter>(parsed.frontmatter);
  const frontmatterRef = useRef<Frontmatter>(parsed.frontmatter);
  useEffect(() => {
    frontmatterRef.current = frontmatter;
  }, [frontmatter]);

  const [suggest, setSuggest] = useState<SuggestState>({
    open: false,
    query: "",
    position: null,
  });
  const editorContainerRef = useRef<HTMLDivElement>(null);

  const editor = useEditor({
    extensions: [
      StarterKit.configure({
        codeBlock: false, // Replaced by CodeBlockLowlight below.
      }),
      Link.configure({
        openOnClick: false,
        autolink: true,
        HTMLAttributes: { class: "text-blue-600 underline" },
      }),
      CodeBlockLowlight.configure({ lowlight }),
      Markdown.configure({
        html: false,
        linkify: true,
        breaks: false,
        transformPastedText: true,
      }),
      WikiLinkExtension.configure({ workspaceId, HTMLAttributes: {} }),
    ],
    content: parsed.body,
    editable: !readOnly,
    immediatelyRender: false,
    editorProps: {
      attributes: {
        class:
          "prose prose-sm max-w-none min-h-[400px] px-4 py-3 focus:outline-none",
        "data-testid": "tiptap-editor",
      },
    },
    onUpdate: ({ editor: ed }) => {
      const md = getMarkdownFromEditor(ed);
      const full = serializeFrontmatter(frontmatterRef.current) + md;
      onChange(full, frontmatterRef.current);
    },
  });

  // Surface frontmatter changes back to the parent without round-tripping
  // through the editor.
  const handleFrontmatterChange = useCallback(
    (next: Frontmatter) => {
      setFrontmatter(next);
      frontmatterRef.current = next;
      const md = editor ? getMarkdownFromEditor(editor) : "";
      onChange(serializeFrontmatter(next) + md, next);
    },
    [editor, onChange],
  );

  // Listen for the WikiLinkExtension's `[[` signal and open the dropdown
  // anchored to the current selection.
  useEffect(() => {
    if (!editor) return;
    function onSuggest(_e: Event) {
      if (!editor) return;
      const { from } = editor.state.selection;
      const coords = editor.view.coordsAtPos(from);
      const containerRect = editorContainerRef.current?.getBoundingClientRect();
      const top = containerRect ? coords.bottom - containerRect.top + 4 : coords.bottom;
      const left = containerRect ? coords.left - containerRect.left : coords.left;
      setSuggest({ open: true, query: "", position: { top, left } });
    }
    window.addEventListener("showWikiLinkSuggest", onSuggest);
    return () => window.removeEventListener("showWikiLinkSuggest", onSuggest);
  }, [editor]);

  const filteredPages = useMemo(() => {
    const q = suggest.query.trim().toLowerCase();
    if (!q) return MOCK_PAGES.slice(0, 6);
    return MOCK_PAGES.filter(
      (p) =>
        p.slug.toLowerCase().includes(q) || p.title.toLowerCase().includes(q),
    ).slice(0, 6);
  }, [suggest.query]);

  const insertWikiLink = (slug: string, title: string) => {
    if (!editor) return;
    editor
      .chain()
      .focus()
      .insertContent({
        type: "text",
        text: title,
        marks: [
          {
            type: "wikiLink",
            attrs: { href: slug, label: title },
          },
        ],
      })
      .run();
    setSuggest({ open: false, query: "", position: null });
  };

  const closeSuggest = () => setSuggest((s) => ({ ...s, open: false }));

  if (!editor) {
    // SSR placeholder — the dynamic-import wrapper in the page still renders this on first paint.
    return (
      <div className="rounded-lg border border-gray-200 bg-white p-6 text-sm text-gray-400">
        {t("loading")}
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <FrontmatterPanel
        frontmatter={frontmatter}
        onChange={handleFrontmatterChange}
        readOnly={readOnly}
      />

      <div className="rounded-lg border border-gray-200 bg-white">
        <Toolbar editor={editor} readOnly={readOnly} t={tToolbar} />
        <div ref={editorContainerRef} className="relative">
          <EditorContent editor={editor} />

          {suggest.open && suggest.position && (
            <div
              data-testid="wikilink-autocomplete-dropdown"
              role="listbox"
              className="absolute z-30 w-72 rounded-lg border border-gray-200 bg-white shadow-lg"
              style={{ top: suggest.position.top, left: suggest.position.left }}
            >
              <div className="p-2 border-b border-gray-100">
                <Input
                  autoFocus
                  value={suggest.query}
                  placeholder={tWikilink("placeholder")}
                  onChange={(e) =>
                    setSuggest((s) => ({ ...s, query: e.target.value }))
                  }
                  onKeyDown={(e) => {
                    if (e.key === "Escape") {
                      e.preventDefault();
                      closeSuggest();
                    }
                  }}
                />
              </div>
              <ul className="max-h-60 overflow-auto py-1">
                {filteredPages.length === 0 ? (
                  <li className="px-3 py-2 text-sm text-gray-400">
                    {tWikilink("noResults")}
                  </li>
                ) : (
                  filteredPages.map((p) => (
                    <li key={p.slug}>
                      <button
                        type="button"
                        onClick={() => insertWikiLink(p.slug, p.title)}
                        className="flex w-full items-start justify-between gap-2 px-3 py-2 text-left text-sm hover:bg-gray-50"
                      >
                        <span className="font-medium text-gray-900">{p.title}</span>
                        <span className="text-xs text-gray-400">{p.slug}</span>
                      </button>
                    </li>
                  ))
                )}
              </ul>
              <div className="border-t border-gray-100 px-3 py-1.5 text-right">
                <button
                  type="button"
                  onClick={closeSuggest}
                  className="text-xs text-gray-500 hover:text-gray-700"
                >
                  Esc
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

interface ToolbarProps {
  editor: Editor;
  readOnly: boolean;
  t: ReturnType<typeof useTranslations>;
}

function Toolbar({ editor, readOnly, t }: ToolbarProps) {
  if (readOnly) return null;

  const ToolbarButton = ({
    onClick,
    active,
    label,
    children,
  }: {
    onClick: () => void;
    active?: boolean;
    label: string;
    children: React.ReactNode;
  }) => (
    <Button
      type="button"
      variant={active ? "secondary" : "ghost"}
      size="icon"
      onClick={onClick}
      title={label}
      aria-label={label}
    >
      {children}
    </Button>
  );

  const promptForLink = () => {
    const previous = editor.getAttributes("link").href as string | undefined;
    const url = window.prompt(t("link"), previous ?? "https://");
    if (url === null) return;
    if (url === "") {
      editor.chain().focus().extendMarkRange("link").unsetLink().run();
      return;
    }
    editor.chain().focus().extendMarkRange("link").setLink({ href: url }).run();
  };

  return (
    <div
      className="flex flex-wrap items-center gap-1 border-b border-gray-200 px-2 py-1.5"
      role="toolbar"
    >
      <ToolbarButton
        onClick={() => editor.chain().focus().toggleBold().run()}
        active={editor.isActive("bold")}
        label={t("bold")}
      >
        <Bold className="h-4 w-4" />
      </ToolbarButton>
      <ToolbarButton
        onClick={() => editor.chain().focus().toggleItalic().run()}
        active={editor.isActive("italic")}
        label={t("italic")}
      >
        <Italic className="h-4 w-4" />
      </ToolbarButton>
      <ToolbarButton onClick={promptForLink} active={editor.isActive("link")} label={t("link")}>
        <LinkIcon className="h-4 w-4" />
      </ToolbarButton>
      <ToolbarButton
        onClick={() => editor.chain().focus().toggleCodeBlock().run()}
        active={editor.isActive("codeBlock")}
        label={t("codeBlock")}
      >
        <Code2 className="h-4 w-4" />
      </ToolbarButton>
      <span className="mx-1 h-5 w-px bg-gray-200" />
      <ToolbarButton
        onClick={() => editor.chain().focus().toggleHeading({ level: 1 }).run()}
        active={editor.isActive("heading", { level: 1 })}
        label={`${t("heading")} 1`}
      >
        <Heading1 className="h-4 w-4" />
      </ToolbarButton>
      <ToolbarButton
        onClick={() => editor.chain().focus().toggleHeading({ level: 2 }).run()}
        active={editor.isActive("heading", { level: 2 })}
        label={`${t("heading")} 2`}
      >
        <Heading2 className="h-4 w-4" />
      </ToolbarButton>
      <ToolbarButton
        onClick={() => editor.chain().focus().toggleHeading({ level: 3 }).run()}
        active={editor.isActive("heading", { level: 3 })}
        label={`${t("heading")} 3`}
      >
        <Heading3 className="h-4 w-4" />
      </ToolbarButton>
      <span className="mx-1 h-5 w-px bg-gray-200" />
      <ToolbarButton
        onClick={() => editor.chain().focus().toggleBulletList().run()}
        active={editor.isActive("bulletList")}
        label={t("bulletList")}
      >
        <List className="h-4 w-4" />
      </ToolbarButton>
      <ToolbarButton
        onClick={() => editor.chain().focus().toggleOrderedList().run()}
        active={editor.isActive("orderedList")}
        label={t("orderedList")}
      >
        <ListOrdered className="h-4 w-4" />
      </ToolbarButton>
    </div>
  );
}

export default WikiEditor;
